### ISSUE TITLE
curl timeouts

### ISSUE THREAD

**Issue by oleh-ozimok** [mailfire/php-sdk#23]
Добавьте, пожалуйста, в клиент возможность задать на постоянной основе CURLOPT_CONNECTTIMEOUT_MS и CURLOPT_TIMEOUT_MS. В текущей реализации клиента, если уставить эти опции через ->setOption(KEY, VALUE), они будут применены только к первому запросу так после него выполняется curl_reset.

**Comment by oleh-ozimok** [comment]
?

**Comment by ercling** [comment]
@oleh-ozimok хорошая идея. В работе

**Comment by ercling** [comment]
@oleh-ozimok добавили в версии 0.1.27:

$mf->request->setOption(CURLOPT_TIMEOUT_MS, 2000, true);

**Comment by oleh-ozimok** [comment]
@ercling спасибо
